#sudo: required -- deprecated
services:
  - docker

language: node_js
node_js:
  - "12.16.2"
 

before_install:
  - docker build -t dnsgom/docker-react -f Dockerfile.dev .

script:
  - docker run dnsgom/docker-react npm run test -- --coverage
