#sudo: required -- deprecated
services:
  - docker
language: node_js
node_js:
- 'lts/*'
before_install:
  - docker build -t dnsgom/docker-react -f Dockerfile.dev .
script:
  #- docker run dnsgom/docker-react npm run test -- --coverage -> deprecated, won´t work. By default npm test runs the watcher with interactive CLI. However, you can force it to run tests once and finish the process by setting an environment variable called CI.
  -  docker run -e CI=true dnsgom/docker-react npm run test
